version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
      time: "14:00"
    open-pull-requests-limit: 3
    reviewers:
      - rathesDot
    labels:
      - dependencies
    groups:
      next:
        patterns:
          - "eslint-config-next"
          - "next"
      tailwindcss:
        patterns:
          - "tailwindcss"
          - "autoprefixer"
          - "postcss"
      jest:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
