[[redirects]]
  from = "/reading-list"
  to = "/reading"
  status = 301
  force = true

[[redirects]]
  from = "/writings"
  to = "/writing"
  status = 301
  force = true

[build.processing]
  skip_processing = true
