import localFont from "next/font/local"
import Fathom from "../components/Fathom"

import "../styles/globals.css"

export const metadata = {
  title: "Rathes Sachchithananthan",
  description: "Generated by Next.js",
}

const switzer = localFont({
  src: "../assets/switzer-variable.ttf",
  variable: "--font-switzer",
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={`${switzer.variable} bg-neutral-950 font-sans text-white`}
      >
        <Fathom />
        {children}
      </body>
    </html>
  )
}
